project:
  type: website

execute:
  freeze: auto
website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - pre_work/index.qmd
      - day_1/index.qmd
      - day_2/index.qmd
      - day_3/index.qmd
      - day_4/index.qmd
    right:
      - text: "Cheat Sheet"
        file: cheat_sheet/cheat_sheet.qmd
      - text: "Resources"
        file: resources.qmd

  sidebar:
    - id: pre_work
      title: "Resources"
      style: "docked"
      background: light
      contents: pre_work
      
    - id: day_1
      title: "Day 1"
      contents: 
        - auto: day_1
        - section: Exercises
          contents:
          - text: Blank
            url:  day_1/exercises/exercises_day_1.R
          - text: Notes from class
            url:  day_1/exercises/exercises_day_1_inclass.R

    - id: day_2
      title: "Day 2"
      contents: day_2

    - id: day_3
      title: "Day 3"
      contents: day_3

    - id: day_4
      title: "Day 4"
      contents: day_4
    
  # sidebar:
  #   style: "floating"
  #   search: true
  #   contents:
  #     - section: "Syllabus"
  #       contents:
  #         - index.qmd
  #     - section: "Pre-work"
  #       contents: pre_work
  #     - section: "Day 1"
  #       contents: day_1
  #   tools:
  #     - icon: twitter
  #       href: https://twitter.com
  #     - icon: github
  #       menu:
  #         - text: Source Code
  #           url:  https://code.com
  #         - text: Report a Bug
  #           url:  https://bugs.com
  #
  #
  #
  #
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  #   right:
  #     - text: Slides
  #       menu: 
  #         - 01-slides.qmd   
  #     - text: Assignments
  #       menu: 
  #         - 01-assignment.qmd

format:
  html:
    theme: [journal, www/custom.scss]
    css: www/styles.css
    toc: true
  revealjs:
    slide-number: c/t
    preview-links: auto
    hash-type: number
    hash-one-based-index: true
    # pdf-max-pages-per-slide: 1
    theme: 
      - www/custom.scss
    pointer:
      color: 'red'
      pointerSize: 16
revealjs-plugins:
  - pointer
  
format-links: false
highlight-style: nord
editor: source
