---
title: "Homework 4"
format: docx
---

Include all of your code in a quarto document (`echo: true`). Render your document to html, docx, or pdf and submit. As always, there are many different ways to solve these problems, but focus on the functions and skills we have been learning in class.

1. Read in the `.csv` file you used for yesterday's homework from <https://github.com/louisahsmith/id543/raw/main/data/nlsy.csv>. This time, read the column names and missing values in directly. Recall that the variables in this dataset correspond to `c("glasses", "eyesight", "sleep_wkdy", "sleep_wknd", "id", "nsibs", "samp", "race_eth", "sex", "region", "income", "res_1980", "res_2002", "age_bir")` in this order. All negative numbers indicate missing values.

2. Create a variable that is 1 if an observation has an income between 20,000 and 30,000, and 0 otherwise. Calculate the proportion of people in the dataset who fit that criterion.

3. Recreate the `summary()` function using `summarize()` (i.e., produce all the same statistics) for the `age_bir` variable. That is, you should get all the same values as `summary(nlsy$age_bir)` but using `summary()` instead

4. Join the full `nlsy` dataset with the kids dataset you read in in class from <https://github.com/louisahsmith/id543/raw/main/data/nlsy-child.csv>. Use a join function that results in all the moms and dads without kids in the dataset included. How many rows does it have?

5. How many of each group are there: a) moms with kids, b) moms without kids, c) dads with kids, d) dads without kids?

6. Here's a code snippet:
```{r}
regions <- tibble(region = 1:4,
                  region_cat = c("Northeast", "North Central", "South", "West"))
```
With this `regions` dataset, use a `join` function to add the `region_cat` variable to the joined parent/kid dataset.

7. Using your `region_cat` variable, calculate the average birthweight in grams within each region.
